{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"tf_callback_example.ipynb","provenance":[],"collapsed_sections":[],"toc_visible":true,"mount_file_id":"1iYDjl4lYKQ54aU0Z7hVolYsme7wEAYmH","authorship_tag":"ABX9TyNKgWFOit6J5uyZzHslA9Xz"},"kernelspec":{"name":"python3","display_name":"Python 3"}},"cells":[{"cell_type":"code","metadata":{"id":"qJEBHpMJLc7m"},"source":["tf.keras.callbacks.Callback?"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"koR4obKfLg2R"},"source":["import tensorflow as tf\n","class myCallback(tf.keras.callbacks.Callback):\n","\tdef on_epoch_end(self, epoch, logs={}):\n","\t\tif (logs.get('accuracy')>0.6):\n","\t\t\tprint('Reached accuracy limit, stopping!')\n","\t\t\tself.model.stop_trainning = True"],"execution_count":null,"outputs":[]}]}